/**
 * Marketplace freshness gate.
 *
 * The plugin marketplace registries (`.claude-plugin/`, `.cursor-plugin/`,
 * `.agents/`) are GENERATED by `aipm build` from the plugin sources + the
 * `aipm.*.ts` config, and committed. If someone edits a plugin source (or a
 * target manifest) without re-running `aipm build`, the committed registries
 * drift. `aipm validate` catches that (plus schema / target-envelope issues);
 * running it here makes the existing `pnpm test` CI job the gate, so we don't
 * need a dedicated workflow step.
 *
 * Fix on failure: `pnpm marketplace:build` and commit the regenerated registries.
 *
 * @see https://github.com/ai-plugin-marketplace
 */
import { execFileSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

describe("plugin marketplace (aipm)", () => {
  it("generated registries are fresh and valid (aipm validate)", () => {
    let ok = true;
    let output = "";
    try {
      output = execFileSync("pnpm", ["exec", "aipm", "validate"], {
        cwd: repoRoot,
        encoding: "utf8",
        timeout: 60_000,
      });
    } catch (e) {
      ok = false;
      const err = e as { stdout?: string; stderr?: string; message?: string };
      output = err.stdout ?? "";
      output += err.stderr ?? err.message ?? "";
    }
    // Surface aipm's findings in the assertion message when it fails.
    expect(ok, `aipm validate reported findings:\n${output}`).toBe(true);
  }, 60_000);
});
