/**
 * Unit tests for buildRRule, repeatMethodToOmniJS, validateRepetitionRule,
 * applyRepetitionRuleDescriptor, and clearRepetitionRuleDescriptor.
 *
 * All expected RRULE strings are derived directly from RFC 5545 §3.3.10 —
 * they are NOT generated by running the code and then asserting on that
 * output.
 *
 * @see https://datatracker.ietf.org/doc/html/rfc5545#section-3.3.10
 */
import { describe, it, expect, vi, beforeEach } from "vitest";
import {
  buildRRule,
  repeatMethodToOmniJS,
  applyRepetitionRuleDescriptor,
  clearRepetitionRuleDescriptor,
} from "../../../src/commands/repetition.js";
import { validateRepetitionRule } from "../../../src/validation.js";
import { ErrorCode } from "../../../src/errors.js";
import type { RepetitionRule } from "../../../src/types.js";
import type { OmniJSResult } from "../../../src/omnijs.js";

// Mock the omnijs module so unit tests never touch OmniFocus
vi.mock("../../../src/omnijs.js", () => ({
  runOmniJSWrapped: vi.fn(),
  escapeJSString: vi.fn((s: string) => s),
  toOmniJSDate: vi.fn((s: string) => `new Date("${s}")`),
}));

import { runOmniJSWrapped } from "../../../src/omnijs.js";

const mockRunOmniJS = vi.mocked(runOmniJSWrapped);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function okResult<T>(data: T): OmniJSResult<T> {
  return { success: true, data };
}

function errResult(message = "OmniFocus not running"): OmniJSResult<never> {
  return { success: false, error: { code: ErrorCode.SCRIPT_ERROR, message } };
}

// ---------------------------------------------------------------------------
// buildRRule — every RRULE variant
// ---------------------------------------------------------------------------

describe("buildRRule", () => {
  describe("daily", () => {
    it("FREQ=DAILY with interval=1 omits INTERVAL", () => {
      // RFC 5545 §3.3.10: default interval is 1 — omitting it is legal
      const rule: RepetitionRule = {
        frequency: "daily",
        interval: 1,
        repeatMethod: "due-again",
      };
      expect(buildRRule(rule)).toBe("FREQ=DAILY");
    });

    it("FREQ=DAILY;INTERVAL=3 when interval=3", () => {
      const rule: RepetitionRule = {
        frequency: "daily",
        interval: 3,
        repeatMethod: "due-again",
      };
      expect(buildRRule(rule)).toBe("FREQ=DAILY;INTERVAL=3");
    });
  });

  describe("weekly", () => {
    it("FREQ=WEEKLY with interval=1 omits INTERVAL", () => {
      const rule: RepetitionRule = {
        frequency: "weekly",
        interval: 1,
        repeatMethod: "due-again",
      };
      expect(buildRRule(rule)).toBe("FREQ=WEEKLY");
    });

    it("FREQ=WEEKLY;BYDAY=MO for single day (Monday=1)", () => {
      const rule: RepetitionRule = {
        frequency: "weekly",
        interval: 1,
        repeatMethod: "due-again",
        daysOfWeek: [1],
      };
      expect(buildRRule(rule)).toBe("FREQ=WEEKLY;BYDAY=MO");
    });

    it("FREQ=WEEKLY;BYDAY=MO,WE,FR for multi-day (Mon=1,Wed=3,Fri=5)", () => {
      // RFC 5545 §3.3.10: BYDAY with multiple day abbreviations
      const rule: RepetitionRule = {
        frequency: "weekly",
        interval: 1,
        repeatMethod: "due-again",
        daysOfWeek: [1, 3, 5],
      };
      expect(buildRRule(rule)).toBe("FREQ=WEEKLY;BYDAY=MO,WE,FR");
    });

    it("FREQ=WEEKLY;INTERVAL=2;BYDAY=MO,FR for biweekly Mon+Fri", () => {
      const rule: RepetitionRule = {
        frequency: "weekly",
        interval: 2,
        repeatMethod: "due-again",
        daysOfWeek: [1, 5],
      };
      expect(buildRRule(rule)).toBe("FREQ=WEEKLY;INTERVAL=2;BYDAY=MO,FR");
    });

    it("all day codes: SU,MO,TU,WE,TH,FR,SA for days [0,1,2,3,4,5,6]", () => {
      const rule: RepetitionRule = {
        frequency: "weekly",
        interval: 1,
        repeatMethod: "due-again",
        daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
      };
      expect(buildRRule(rule)).toBe("FREQ=WEEKLY;BYDAY=SU,MO,TU,WE,TH,FR,SA");
    });

    it("omits BYDAY when daysOfWeek is empty array", () => {
      const rule: RepetitionRule = {
        frequency: "weekly",
        interval: 1,
        repeatMethod: "due-again",
        daysOfWeek: [],
      };
      expect(buildRRule(rule)).toBe("FREQ=WEEKLY");
    });

    it("omits BYDAY when daysOfWeek is undefined", () => {
      const rule: RepetitionRule = {
        frequency: "weekly",
        interval: 1,
        repeatMethod: "due-again",
      };
      expect(buildRRule(rule)).toBe("FREQ=WEEKLY");
    });
  });

  describe("monthly", () => {
    it("FREQ=MONTHLY;BYMONTHDAY=15 for day-of-month", () => {
      // RFC 5545 §3.3.10: BYMONTHDAY specifies an ordinal within the month
      const rule: RepetitionRule = {
        frequency: "monthly",
        interval: 1,
        repeatMethod: "due-again",
        dayOfMonth: 15,
      };
      expect(buildRRule(rule)).toBe("FREQ=MONTHLY;BYMONTHDAY=15");
    });

    it("FREQ=MONTHLY;BYDAY=1MO — first Monday (positional single)", () => {
      // RFC 5545 §3.3.10: BYDAY with numeric prefix = Nth occurrence of weekday in month
      const rule: RepetitionRule = {
        frequency: "monthly",
        interval: 1,
        repeatMethod: "due-again",
        daysOfWeek: [1],
        daysOfWeekPositions: [1],
      };
      expect(buildRRule(rule)).toBe("FREQ=MONTHLY;BYDAY=1MO");
    });

    it("FREQ=MONTHLY;BYDAY=1MO,-1MO — first and last Monday (multi-position, single day)", () => {
      const rule: RepetitionRule = {
        frequency: "monthly",
        interval: 1,
        repeatMethod: "due-again",
        daysOfWeek: [1],
        daysOfWeekPositions: [1, -1],
      };
      expect(buildRRule(rule)).toBe("FREQ=MONTHLY;BYDAY=1MO,-1MO");
    });

    it("FREQ=MONTHLY;BYDAY=1MO,1WE,-1MO,-1WE — cross-product (positions=[1,-1], days=[1,3])", () => {
      // positions outermost: 1×MO, 1×WE, -1×MO, -1×WE
      const rule: RepetitionRule = {
        frequency: "monthly",
        interval: 1,
        repeatMethod: "due-again",
        daysOfWeek: [1, 3],
        daysOfWeekPositions: [1, -1],
      };
      expect(buildRRule(rule)).toBe("FREQ=MONTHLY;BYDAY=1MO,1WE,-1MO,-1WE");
    });

    it("cross-product deduplicates when positions and days overlap", () => {
      // positions=[1,1] × days=[1] should deduplicate to BYDAY=1MO
      const rule: RepetitionRule = {
        frequency: "monthly",
        interval: 1,
        repeatMethod: "due-again",
        daysOfWeek: [1],
        daysOfWeekPositions: [1, 1],
      };
      expect(buildRRule(rule)).toBe("FREQ=MONTHLY;BYDAY=1MO");
    });

    it("FREQ=MONTHLY;INTERVAL=3;BYMONTHDAY=1 — quarterly on day 1", () => {
      const rule: RepetitionRule = {
        frequency: "monthly",
        interval: 3,
        repeatMethod: "due-again",
        dayOfMonth: 1,
      };
      expect(buildRRule(rule)).toBe("FREQ=MONTHLY;INTERVAL=3;BYMONTHDAY=1");
    });
  });

  describe("yearly", () => {
    it("FREQ=YEARLY with interval=1 omits INTERVAL", () => {
      const rule: RepetitionRule = {
        frequency: "yearly",
        interval: 1,
        repeatMethod: "due-again",
      };
      expect(buildRRule(rule)).toBe("FREQ=YEARLY");
    });

    it("FREQ=YEARLY;BYMONTH=3,6,9,12 — quarterly months (March,Jun,Sep,Dec)", () => {
      // RFC 5545 §3.3.10: BYMONTH specifies month of year (1=Jan, 12=Dec)
      const rule: RepetitionRule = {
        frequency: "yearly",
        interval: 1,
        repeatMethod: "due-again",
        monthsOfYear: [3, 6, 9, 12],
      };
      expect(buildRRule(rule)).toBe("FREQ=YEARLY;BYMONTH=3,6,9,12");
    });

    it("FREQ=YEARLY;BYMONTH=12;BYMONTHDAY=25 — Christmas Day", () => {
      const rule: RepetitionRule = {
        frequency: "yearly",
        interval: 1,
        repeatMethod: "due-again",
        monthsOfYear: [12],
        dayOfMonth: 25,
      };
      expect(buildRRule(rule)).toBe("FREQ=YEARLY;BYMONTH=12;BYMONTHDAY=25");
    });
  });
});

// ---------------------------------------------------------------------------
// repeatMethodToOmniJS
// ---------------------------------------------------------------------------

describe("repeatMethodToOmniJS", () => {
  it("maps due-again → Task.RepetitionMethod.DueDate", () => {
    expect(repeatMethodToOmniJS("due-again")).toBe(
      "Task.RepetitionMethod.DueDate"
    );
  });

  it("maps defer-another → Task.RepetitionMethod.Start", () => {
    // Regression: previous callers incorrectly used DeferDate for defer-another.
    // The correct OmniJS constant for "defer-another" is Task.RepetitionMethod.Start.
    expect(repeatMethodToOmniJS("defer-another")).toBe(
      "Task.RepetitionMethod.Start"
    );
  });

  it("maps scheduled → Task.RepetitionMethod.Fixed", () => {
    expect(repeatMethodToOmniJS("scheduled")).toBe(
      "Task.RepetitionMethod.Fixed"
    );
  });
});

// ---------------------------------------------------------------------------
// validateRepetitionRule — new fields
// ---------------------------------------------------------------------------

describe("validateRepetitionRule — new fields", () => {
  describe("repeatMethod: scheduled", () => {
    it("accepts scheduled as a valid method", () => {
      const result = validateRepetitionRule({
        frequency: "daily",
        interval: 1,
        repeatMethod: "scheduled",
      });
      expect(result).toBeNull();
    });

    it("rejects unknown method values", () => {
      const result = validateRepetitionRule({
        frequency: "daily",
        interval: 1,
        repeatMethod: "never",
      });
      expect(result).not.toBeNull();
      expect(result?.code).toBe(ErrorCode.VALIDATION_ERROR);
      expect(result?.message).toContain("Invalid repeat method");
    });
  });

  describe("daysOfWeekPositions", () => {
    it("accepts valid positions on monthly frequency", () => {
      const result = validateRepetitionRule({
        frequency: "monthly",
        interval: 1,
        repeatMethod: "due-again",
        daysOfWeek: [1],
        daysOfWeekPositions: [1, -1, 2, -2, 5],
      });
      expect(result).toBeNull();
    });

    it("rejects daysOfWeekPositions when frequency is daily", () => {
      const result = validateRepetitionRule({
        frequency: "daily",
        interval: 1,
        repeatMethod: "due-again",
        daysOfWeekPositions: [1],
      });
      expect(result).not.toBeNull();
      expect(result?.code).toBe(ErrorCode.VALIDATION_ERROR);
      expect(result?.message).toContain(
        "daysOfWeekPositions is only valid for monthly frequency"
      );
    });

    it("rejects daysOfWeekPositions when frequency is weekly", () => {
      const result = validateRepetitionRule({
        frequency: "weekly",
        interval: 1,
        repeatMethod: "due-again",
        daysOfWeekPositions: [1],
      });
      expect(result).not.toBeNull();
      expect(result?.message).toContain(
        "daysOfWeekPositions is only valid for monthly frequency"
      );
    });

    it("rejects daysOfWeekPositions when frequency is yearly", () => {
      const result = validateRepetitionRule({
        frequency: "yearly",
        interval: 1,
        repeatMethod: "due-again",
        daysOfWeekPositions: [1],
      });
      expect(result).not.toBeNull();
      expect(result?.message).toContain(
        "daysOfWeekPositions is only valid for monthly frequency"
      );
    });

    it("rejects out-of-range position 0", () => {
      const result = validateRepetitionRule({
        frequency: "monthly",
        interval: 1,
        repeatMethod: "due-again",
        daysOfWeekPositions: [0],
      });
      expect(result).not.toBeNull();
      expect(result?.message).toContain("Invalid day-of-week position: 0");
    });

    it("rejects out-of-range position 6", () => {
      const result = validateRepetitionRule({
        frequency: "monthly",
        interval: 1,
        repeatMethod: "due-again",
        daysOfWeekPositions: [6],
      });
      expect(result).not.toBeNull();
      expect(result?.message).toContain("Invalid day-of-week position: 6");
    });

    it("rejects out-of-range position -6", () => {
      const result = validateRepetitionRule({
        frequency: "monthly",
        interval: 1,
        repeatMethod: "due-again",
        daysOfWeekPositions: [-6],
      });
      expect(result).not.toBeNull();
      expect(result?.message).toContain("Invalid day-of-week position: -6");
    });

    it("accepts boundary positions -5 and 5 with daysOfWeek", () => {
      const result = validateRepetitionRule({
        frequency: "monthly",
        interval: 1,
        repeatMethod: "due-again",
        daysOfWeek: [1], // required when daysOfWeekPositions is set
        daysOfWeekPositions: [-5, 5],
      });
      expect(result).toBeNull();
    });

    it("rejects empty daysOfWeekPositions array", () => {
      const result = validateRepetitionRule({
        frequency: "monthly",
        interval: 1,
        repeatMethod: "due-again",
        daysOfWeekPositions: [],
      });
      expect(result).not.toBeNull();
      expect(result?.message).toContain(
        "daysOfWeekPositions must be a non-empty array"
      );
    });

    // Regression test: silent-drop bug — without daysOfWeek, buildRRule emits only
    // FREQ=MONTHLY, silently dropping the Nth-weekday constraint entirely.
    // Reported via Copilot review of packages/sdk/src/validation.ts:259.
    it("rejects daysOfWeekPositions without daysOfWeek (silent-drop bug)", () => {
      const result = validateRepetitionRule({
        frequency: "monthly",
        interval: 1,
        repeatMethod: "due-again",
        daysOfWeekPositions: [1],
      });
      expect(result).not.toBeNull();
      expect(result?.code).toBe(ErrorCode.VALIDATION_ERROR);
      expect(result?.message).toContain("daysOfWeek");
    });

    it("accepts daysOfWeekPositions when daysOfWeek is also set (valid Nth-weekday combination)", () => {
      const result = validateRepetitionRule({
        frequency: "monthly",
        interval: 1,
        repeatMethod: "due-again",
        daysOfWeekPositions: [1],
        daysOfWeek: [1], // first Monday of the month
      });
      expect(result).toBeNull();
    });
  });

  describe("monthsOfYear", () => {
    it("accepts valid months on yearly frequency", () => {
      const result = validateRepetitionRule({
        frequency: "yearly",
        interval: 1,
        repeatMethod: "due-again",
        monthsOfYear: [1, 6, 12],
      });
      expect(result).toBeNull();
    });

    it("rejects monthsOfYear when frequency is monthly", () => {
      const result = validateRepetitionRule({
        frequency: "monthly",
        interval: 1,
        repeatMethod: "due-again",
        monthsOfYear: [3],
      });
      expect(result).not.toBeNull();
      expect(result?.message).toContain(
        "monthsOfYear is only valid for yearly frequency"
      );
    });

    it("rejects monthsOfYear when frequency is weekly", () => {
      const result = validateRepetitionRule({
        frequency: "weekly",
        interval: 1,
        repeatMethod: "due-again",
        monthsOfYear: [6],
      });
      expect(result).not.toBeNull();
      expect(result?.message).toContain(
        "monthsOfYear is only valid for yearly frequency"
      );
    });

    it("rejects month 0 (out of range)", () => {
      const result = validateRepetitionRule({
        frequency: "yearly",
        interval: 1,
        repeatMethod: "due-again",
        monthsOfYear: [0],
      });
      expect(result).not.toBeNull();
      expect(result?.message).toContain("Invalid month of year: 0");
    });

    it("rejects month 13 (out of range)", () => {
      const result = validateRepetitionRule({
        frequency: "yearly",
        interval: 1,
        repeatMethod: "due-again",
        monthsOfYear: [13],
      });
      expect(result).not.toBeNull();
      expect(result?.message).toContain("Invalid month of year: 13");
    });

    it("accepts boundary months 1 and 12", () => {
      const result = validateRepetitionRule({
        frequency: "yearly",
        interval: 1,
        repeatMethod: "due-again",
        monthsOfYear: [1, 12],
      });
      expect(result).toBeNull();
    });

    it("rejects empty monthsOfYear array", () => {
      const result = validateRepetitionRule({
        frequency: "yearly",
        interval: 1,
        repeatMethod: "due-again",
        monthsOfYear: [],
      });
      expect(result).not.toBeNull();
      expect(result?.message).toContain(
        "monthsOfYear must be a non-empty array"
      );
    });
  });

  describe("existing fields still validated", () => {
    it("rejects invalid interval (0)", () => {
      const result = validateRepetitionRule({
        frequency: "daily",
        interval: 0,
        repeatMethod: "due-again",
      });
      expect(result).not.toBeNull();
      expect(result?.message).toContain("Invalid repetition interval");
    });

    it("rejects invalid frequency", () => {
      const result = validateRepetitionRule({
        frequency: "hourly",
        interval: 1,
        repeatMethod: "due-again",
      });
      expect(result).not.toBeNull();
      expect(result?.message).toContain("Invalid repetition frequency");
    });

    it("accepts undefined rule (nothing to validate)", () => {
      expect(validateRepetitionRule(undefined)).toBeNull();
    });
  });
});

// ---------------------------------------------------------------------------
// applyRepetitionRuleDescriptor — metadata + OmniJS body
// ---------------------------------------------------------------------------

describe("applyRepetitionRuleDescriptor", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("has correct cliName", () => {
    expect(applyRepetitionRuleDescriptor.cliName).toBe("apply-repetition");
  });

  it("has correct mcpName", () => {
    expect(applyRepetitionRuleDescriptor.mcpName).toBe("task_apply_repetition");
  });

  it("lists taskId as the first positional", () => {
    expect(applyRepetitionRuleDescriptor.cliPositional[0]).toBe("taskId");
  });

  it("returns error for invalid task ID format", async () => {
    const result = await applyRepetitionRuleDescriptor.handler({
      taskId: 'invalid"id',
      frequency: "daily",
      interval: 1,
      repeatMethod: "due-again",
    });

    expect(result.success).toBe(false);
    expect(result.error?.code).toBe(ErrorCode.INVALID_ID_FORMAT);
    expect(mockRunOmniJS).not.toHaveBeenCalled();
  });

  it("returns error for invalid repeatMethod", async () => {
    const result = await applyRepetitionRuleDescriptor.handler({
      taskId: "abc123",
      frequency: "daily",
      interval: 1,
      repeatMethod: "never" as "due-again",
    });

    expect(result.success).toBe(false);
    expect(result.error?.code).toBe(ErrorCode.VALIDATION_ERROR);
    expect(mockRunOmniJS).not.toHaveBeenCalled();
  });

  it("emits correct OmniJS body for a daily rule", async () => {
    mockRunOmniJS.mockResolvedValueOnce(
      okResult({
        id: "task123",
        ruleString: "FREQ=DAILY",
        method: "Task.RepetitionMethod.DueDate",
      })
    );

    await applyRepetitionRuleDescriptor.handler({
      taskId: "task123",
      frequency: "daily",
      interval: 1,
      repeatMethod: "due-again",
    });

    const body = mockRunOmniJS.mock.calls[0]?.[0] as string;
    expect(body).toContain('Task.byIdentifier("task123")');
    expect(body).toContain(
      'new Task.RepetitionRule("FREQ=DAILY", Task.RepetitionMethod.DueDate)'
    );
  });

  it("emits correct OmniJS body for a monthly Nth-weekday rule (1MO)", async () => {
    mockRunOmniJS.mockResolvedValueOnce(
      okResult({
        id: "t1",
        ruleString: "FREQ=MONTHLY;BYDAY=1MO",
        method: "Task.RepetitionMethod.Start",
      })
    );

    await applyRepetitionRuleDescriptor.handler({
      taskId: "t1",
      frequency: "monthly",
      interval: 1,
      repeatMethod: "defer-another",
      daysOfWeek: [1],
      daysOfWeekPositions: [1],
    });

    const body = mockRunOmniJS.mock.calls[0]?.[0] as string;
    expect(body).toContain(
      'new Task.RepetitionRule("FREQ=MONTHLY;BYDAY=1MO", Task.RepetitionMethod.Start)'
    );
  });

  it("emits correct OmniJS body for a yearly rule with BYMONTH", async () => {
    mockRunOmniJS.mockResolvedValueOnce(
      okResult({
        id: "t2",
        ruleString: "FREQ=YEARLY;BYMONTH=12;BYMONTHDAY=25",
        method: "Task.RepetitionMethod.Fixed",
      })
    );

    await applyRepetitionRuleDescriptor.handler({
      taskId: "t2",
      frequency: "yearly",
      interval: 1,
      repeatMethod: "scheduled",
      monthsOfYear: [12],
      dayOfMonth: 25,
    });

    const body = mockRunOmniJS.mock.calls[0]?.[0] as string;
    expect(body).toContain(
      'new Task.RepetitionRule("FREQ=YEARLY;BYMONTH=12;BYMONTHDAY=25", Task.RepetitionMethod.Fixed)'
    );
  });

  it("returns failure when OmniJS errors", async () => {
    mockRunOmniJS.mockResolvedValueOnce(errResult("OmniFocus not running"));

    const result = await applyRepetitionRuleDescriptor.handler({
      taskId: "abc123",
      frequency: "daily",
      interval: 1,
      repeatMethod: "due-again",
    });

    expect(result.success).toBe(false);
    expect(result.error?.message).toBe("OmniFocus not running");
  });
});

// ---------------------------------------------------------------------------
// clearRepetitionRuleDescriptor — metadata + OmniJS body
// ---------------------------------------------------------------------------

describe("clearRepetitionRuleDescriptor", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("has correct cliName", () => {
    expect(clearRepetitionRuleDescriptor.cliName).toBe("clear-repetition");
  });

  it("has correct mcpName", () => {
    expect(clearRepetitionRuleDescriptor.mcpName).toBe("task_clear_repetition");
  });

  it("lists taskId as the first positional", () => {
    expect(clearRepetitionRuleDescriptor.cliPositional[0]).toBe("taskId");
  });

  it("returns error for invalid task ID format", async () => {
    const result = await clearRepetitionRuleDescriptor.handler({
      taskId: 'bad"id',
    });

    expect(result.success).toBe(false);
    expect(result.error?.code).toBe(ErrorCode.INVALID_ID_FORMAT);
    expect(mockRunOmniJS).not.toHaveBeenCalled();
  });

  it("emits OmniJS body that sets repetitionRule to null", async () => {
    mockRunOmniJS.mockResolvedValueOnce(okResult({ id: "task123" }));

    await clearRepetitionRuleDescriptor.handler({ taskId: "task123" });

    const body = mockRunOmniJS.mock.calls[0]?.[0] as string;
    expect(body).toContain('Task.byIdentifier("task123")');
    expect(body).toContain("task.repetitionRule = null");
  });

  it("returns { id } on success", async () => {
    mockRunOmniJS.mockResolvedValueOnce(okResult({ id: "task123" }));

    const result = await clearRepetitionRuleDescriptor.handler({
      taskId: "task123",
    });

    expect(result.success).toBe(true);
    expect(result.data).toEqual({ id: "task123" });
  });

  it("returns failure when OmniJS errors", async () => {
    mockRunOmniJS.mockResolvedValueOnce(errResult("Script error"));

    const result = await clearRepetitionRuleDescriptor.handler({
      taskId: "abc123",
    });

    expect(result.success).toBe(false);
    expect(result.error?.message).toBe("Script error");
  });
});
